import pandas as pd

df = pd.read_csv("data/Coursera.csv")

print("Shape:")
print(df.shape)
print("\nColumns:")
print(df.columns.tolist())
print("\nData types:")
print(df.dtypes)
print("\nMissing values:")
print(df.isnull().sum())
print("\nFirst 5 rows:")
print(df.head())
print("\nDifficulty distribution:")
print(df["Difficulty Level"].value_counts())
print("\nUniversities:")
print(df["University"].nunique())
print("\nDuplicate rows:")
print(df.duplicated().sum())
